from src.analyzers.correlation import *
from src.analyzers.histogram import *
from src.analyzers.kmeans import *
from src.analyzers.shapiro import *
from src.analyzers.abstractanalyzer import AbstractAnalyzer
from src.analyzers.groupcompare import GroupCompareAnalyzer
from src.analyzers.agglomerativeclustering import AgglomerativeClusteringAnalyzer
from src.analyzers.pca import PCAAnalyzer
from src.analyzers.umap import UMAPAnalyzer
